import { makeStyles } from "tss-react/mui";

import { TRANSITION_ANIMATION } from "../../utils/constants";

export const useStyles = makeStyles()((theme) => ({
  container: {
    border: "none",
    display: "inline-flex",
    padding: "0",
    position: "relative",
    minWidth: "0",
    flexDirection: "column",
    verticalAlign: "top",
    width: "100%",
  },
  font: {
    fontFamily: "'Roboto', 'Helvetica', 'Arial', sans-serif",
    fontWeight: "400",
    letterSpacing: "0.00938em",
    fontSize: "1rem",
  },
  label: {
    backgroundColor: theme.palette.background.paper,
    transition: `background-color ${TRANSITION_ANIMATION}, color ${TRANSITION_ANIMATION}`,
    transform: "translate(14px, -6px) scale(0.75)",
    transformOrigin: "top left",
    zIndex: "1",
    top: "0",
    left: "0",
    position: "absolute",
    display: "block",
    color: theme.palette.text.primary,
    lineHeight: "1",
    paddingInlineStart: "5px",
    paddingInlineEnd: "7px",
  },
  root: {
    color: "rgba(0, 0, 0, 0.87)",
    cursor: "text",
    display: "inline-flex",
    position: "relative",
    boxSizing: "border-box",
    alignItems: "center",
    width: "100%",
  },
  input: {
    color: theme.palette.text.primary,
    lineHeight: "1em",
    width: "100%",
    height: "1em",
    margin: "0",
    display: "block",
    padding: "10.5px 14px",
    minWidth: "0",
    background: "none",
    boxSizing: "content-box",
    textRendering: "auto",
    cursor: "text",
    borderRadius: theme.shape.borderRadius,
    border: `1px solid ${
      theme.palette.mode === "dark"
        ? "rgba(255, 255, 255, 0.23)"
        : "rgba(0, 0, 0, 0.23)"
    }`,
    transition: `color ${TRANSITION_ANIMATION}, border ${TRANSITION_ANIMATION}`,
  },
  inputOutline: {
    outline: "0",
    border: `2px solid ${theme.palette.primary.main}`,
    borderBottom: "none",
    borderBottomLeftRadius: "0",
    borderBottomRightRadius: "0",
  },
  labelOutline: {
    color: theme.palette.primary.main,
    transition: `color ${TRANSITION_ANIMATION}`,
  },
  listContainer: {
    paddingTop: "10px",
    overflow: "auto",
    border: `2px solid ${theme.palette.primary.main}`,
    borderTop: `1px solid ${theme.palette.primary.main}`,
    borderTopLeftRadius: "0",
    borderTopRightRadius: "0",
    transition: `border ${TRANSITION_ANIMATION}`,
  },
  item: {
    display: "flex",
    alignItems: "center",
    color: theme.palette.text.primary,
    lineHeight: "1em",
    border: "0",
    height: "1em",
    margin: "0",
    padding: "8px 14px",
    minWidth: "0",
    background: "none",
    boxSizing: "content-box",
    textRendering: "auto",
    cursor: "text",
    transition: `color ${TRANSITION_ANIMATION}`,
  },
}));
